### ISSUE TITLE
Current page gets occluded when animating transitioning pages

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#113]
I.e. next page is over current page during animation.

Change z-order? Animate all pages instead of just pre-existing ones?

**Comment by scottkellum** [comment]
New elements break CSS transitions. May have to create a a blank page container or quickly load the element > then transition it.

**Comment by fortes** [comment]
Can you clarify here? What do you mean by new elements? Do you mean new pages/grids? And what is breaking exactly?

**Comment by scottkellum** [comment]
new DOM elements. and elements that change display — like going from display:none to display:block will not animate.

I am not in the JS so I don't know how exactly you are doing this transition but it looks like a broken CSS transition to me.

changed z-index to make things not so jarring.

**Comment by fortes** [comment]
You had pages set to display: none?

**Comment by scottkellum** [comment]
are new pages being loaded in from .offscreen? That was visability:hidden but I removed that style, still not working...

**Comment by fortes** [comment]
The .offscreen rule is now built in to the code, you no longer have set it manually.

Where is this happening? Can you isolate so I can test?

**Comment by scottkellum** [comment]
It is happening in Safari, mobile safari, chrome... — everywhere css transitions are used.

What is happening exactly is on a page transition the new page being loaded into DOM just pops into place instead of animating. It is subtle but slightly annoying, especially where pages are different sizes like in slideshows or where transitions may be happening slower like slowly swiping on the iPad.
