### ISSUE TITLE
minWidth and minHeight on Figure for Lightbox

### ISSUE THREAD

**Issue by aliciaduffy** [Treesaver/treesaver#157]
To make lightbox work correctly the documentation says to add minWidth and minHeight to the figure, would that be the minWidth / height of the enlarged image or the image that fits in the column?

Thanks!

**Comment by fortes** [comment]
The `figure` probably has multiple versions of each image -- use the `minWidth` and `minHeight` for each version of that image in the markup -- then Treesaver will pick the largest one that could possibly fit.

Note: I'm going to close this ticket since it isn't an actual bug -- the best bet for questions like this is on the mailing list: http://groups.google.com/group/treesaverjs

Thanks!

**Comment by aliciaduffy** [comment]
Thank you for the help, sorry for posting in the wrong place!
