### ISSUE TITLE
Consider adding support for Article # & count binding in Chrome

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#190]
Might want an article count along w/ page count. See mock: http://mattdempsey.com/clients/nomad-editions/magazine/1/

**Comment by bramstein** [comment]
You can now get the document count and document number by binding to the `position` template:

```
<span data-template="position">Document {{documentnumber}} of {{documentcount}}</span>
```

A document is roughly equivalent to an article in the old code. The difference is that you can have more than one article within a document. Since we don't know the number of articles before loading the article, the documentcount and documentnumber are the correct figures if you only use one article per document. Should we expose the article count and article number as well? It would only make sense for single document publications...

**Comment by bramstein** [comment]
I assume this is satisfactory. Note that there is also a `currentdocument` template which gives you the meta-data of the current document (from the JSON.)
