### ISSUE TITLE
Image flow problems

### ISSUE THREAD

**Issue by rajnarayan** [Treesaver/treesaver#223]
I'm having trouble making sure that my images do not get split up into multiple columns. Is there a way to force treesaver to not flow images across multiple columns?

I've tried to use this
https://github.com/Treesaver/treesaver/wiki/Content-Format

keeptogether: Do not let this element be split up across columns (when possible)

**Comment by fortes** [comment]
The best way is to use a Figure: https://github.com/Treesaver/treesaver/wiki/Figure

There's an example in the walkthrough: https://github.com/Treesaver/treesaver/wiki/Walkthrough

Note, please use the Google Group for support questions: http://groups.google.com/group/treesaverjs

(Closing this bug since it's a question)
