### ISSUE TITLE
Support image cloaking via data-src within resources

### ISSUE THREAD

**Issue by sop** [Treesaver/treesaver#257]
Braces in attributes end up url-encoded when html is processed in browser (at least on firefox), eg. {{url}} becomes %7B%7Burl%7D%7D.
Thus Mustache fails to replace tags as intended.
Furthermore having tag in img src in resources file, browser tries to load that as an uri when html is injected to the document, eg. &lt;img src="{{thumb}}" /&gt; attempts to load {{thumb}} (relative url) from the server, which produces unnecessary 404.

**Comment by fortes** [comment]
In the 0.9.3 builds, use `{{$ url $}}` syntax for url-encoded values.

We need to enable the use of `data-src` within a resource. Retitling this issue for that request.

**Comment by sop** [comment]
Actually <code>{{$url$}}</code> has nothing to do with the issue.
Let me elaborate the case with a following piece of code:

<pre><code>var content = '&lt;img src="{{$url$}}" /&gt;';
el.innerHTML = content;   //el is reference to dom node
content = el.innerHTML;   //content is now '&lt;img src="%7B%7B$url$%7D%7D"&gt;'</code></pre>

This issue apparently occurs only in Firefox though, and only with attributes that contain urls (src, href). Thus <code>&lt;a href="{{url}}"&gt;</code> doesn't work either.

I think this raises a question whether mustache is the right tool for the purpose, given it processes on raw text rather than nodes. Problem is that resources html is already parsed by browser, and later it's rebuild to text via innerHTML accessor (no longer necessarily equal, as seen above) and then passed through template engine.

**Comment by fortes** [comment]
OK, I misunderstood at first. Here's what I think is going on, but please correct me if I'm wrong:
1. We need to support using the `data-src` property for images within the resources file, as we do with Figures. This is what this current ticket will track (#257). This will resolve the first of your issues by not causing a loose 404 for an image request.
2. Treesaver looks for the `data-template` property on elements in order to know which need to be processed via Mustache. If you make sure you're mustache'd content lives within an element with the right `data-template`, you should be fine. You can see this in action here: https://github.com/Treesaver/treesaver/blob/master/examples/simple/resources.html

``` html
<div class="toc" data-ts-template="index">
  {{#contents}}
    {{^hidden}}
      <div class="article">
        <img class="thumb" src="{{thumb}}"/>
        <h3><a href="{{url}}">{{title}}</a></h3>
        <p class="byline">{{byline}}</p>
      </div>
    {{/hidden}}
  {{/contents}}
</div>
```

Does that match up correctly with what you're saying? (Pardon my denseness, I'm a bit sleep deprived)

**Comment by sop** [comment]
I agree <code>data-src</code> is the way to go to avoid incorrect http request before template is processed.

But i think you haven't quite yet understood the second issue here :).
Go ahead and browse (with Firefox that is) "simple" from examples folder. Open sidebar and you'll see that thumbnails don't show and clicking an item doesn't bring you an appropriate article, since the link yields <code>treesaver/examples/simple/{{url}}</code> url from href attribute.
However title and byline tags are replaced correctly as intended, because they don't end up url-encoded in browser parsing stage, when resources html is injected to dom tree.

Here's some html from sidebar after mustache processing:

``` html
<div class="article">
    <img src="%7B%7Bthumb%7D%7D" class="thumb">
    <h3><a href="%7B%7Burl%7D%7D">Article One</a></h3>
    <p class="byline">John Doe</p>
</div>
```

**Comment by sop** [comment]
After playing around i can't really come up with a satisfying hack.
To use string templates for innerHTML'd content, the only way really is to pick mustache tag delimiters that don't get encoded. Furthermore as Firefox normalizes src and href attributes (since they're supposed to be valid urls), delimiters should not contain reserved characters, ie. mustache tag should "look" like a valid relative uri.

So i changed <code>otag</code> and <code>ctag</code> in Mustache configuration to <code>--</code>, and in effect tags in resources html to <code>--tag--</code>. As <code>--url--</code> is a valid url, doesn't contain reserved characters and doesn't get encoded, it works, albeit being ugly and unreadable.

``` html
<img class="thumb" src="--thumb--" />
```

Anyway, i doubt there's a generic solution, since the problem behind is that innerHTML **is not** the original source code but rather browser's representation of the internal dom tree converted to a string.
I found following discussion regarding similar issue: http://www.ruby-forum.com/topic/105837#237606

**Comment by bramstein** [comment]
@sop You are right, this is a problem in Firefox. I don't think switching the tag delimiters is the right solution. I was thinking about hacking Mustache to also recognize URL encoded versions of its tag delimiters. We already maintain our own version of Mustache, so it shouldn't add that much overhead. Whether it is pretty is another question.

@fortes Our previous (homegrown) template engine actually operated on nodes instead of text and thus avoided this issue. I'm not entirely sure if Mustache is the right choice for us in the long run. I had high hopes for something like Weld (https://github.com/hij1nx/weld) but development seems to have stalled a bit. A while ago I reviewed some template engines with our use cases in mind:
- Our old template engine: https://gist.github.com/956769 
- Tempo: https://gist.github.com/955511
- Mustache.js: https://gist.github.com/955508

I tried a bunch of others, but none of them supported all our use-cases. I think we then decided to go with Mustache because it is the most popular one.

**Comment by bramstein** [comment]
I guess the other alternative is to wrap the templates in `<script type="text/html">...</script>` like we had before.

**Comment by sop** [comment]
I've actually played quite a bit with 0.9.2 before i tried the master branch. I had no idea what was changed since then and well, it was a bit of a shock :).
Frankly i think 0.9.2 way of dealing with resources templating (with data-bind) seemed enough, i don't know why you changed it in the first place, flexibility i guess?

Hacking mustache to accept url encoded delimiters sounds rather dirty :(. And well, it's a hack. What if some major browser changes the way url attributes are normalized, eg. relative urls are extended to current domain and path, so <code>{{url}}</code> becomes <code>http://domain.com/relative/path/{{url}} </code>.

**Comment by bramstein** [comment]
We changed it because we didn't really want to maintain our own template engine. I agree that hacking Mustache.js is ugly, but it would suffice for people who insists to put templates in `href` or `src` attributes. I guess the best option is to expand the usage of the `data-href` and `data-src` attributes and promote them as the recommended way to bind data to the `src` and `href` attributes.

So:

``` html
<div class="toc" data-ts-template="index">
  {{#contents}}
    {{^hidden}}
      <div class="article">
        <img class="thumb" data-src="{{thumb}}"/>
        <h3><a data-href="{{url}}">{{title}}</a></h3>
        <p class="byline">{{byline}}</p>
      </div>
    {{/hidden}}
  {{/contents}}
</div>
```

would become the recommended way.

**Comment by fortes** [comment]
@sop thanks for your patience here -- after a good night's sleep, I get what's going on here :)

Here is my take on what's the _minimum_ we could do in this situation:
1. We need to support `data-href`, `data-src`, etc for any attribute that is a URL or may otherwise be encoded by the browser
2. We should support `<script>` cloaked templates as an option for authors as well

Requires a bit more documentation, but not much more than explaining to use Mustache and `data-template`.

As for other template engines, I feel pretty strongly that we shouldn't re-invent the wheel here. We've got very limited resources and there's no reason to waste them in coming up with some new template engine that no one else uses. If we can leverage some other project's well-tested code (and documentation), then all the better for us.

Of course, we need to make sure that whatever engine we use fits our scenarios while being well-maintained and documented. Mustache at the time was closest (also has a large amount of use). Handlebars was considered, but the download is far too large.

I'm open to looking into other engines, of course. Tough to find ones that are relatively small while having the features we need. Underscore's templates are very simple and fast in terms of code, but without nice looping constructs, we force resources HTML authors to write JS inline, which is error-prone.

**Comment by sop** [comment]
Well you know best what you're dealing with :).
<code>data-*</code> solution for url attributes fixes both original issues i guess, and it's definitely easiest and fastest to implement.
Still, i find it awkward to use string based template engine for innerHTML, kinda like parsing HTML with regular expressions (which it actually is...). Maybe dom based engine is something to look forward for 2.0 :)

**Comment by fortes** [comment]
@sop If you find a compelling DOM-based template engine, do let us know. The 0.9.2 engine had some limitations that made it tough to support common scenarios.

**Comment by bramstein** [comment]
See SHA: ee683faa5c243dc77fbc7847a03cb933360721fe 

Treesaver now supports the `data-href` and `data-src` attributes which will be expanded to `href` and `src`. Additionally you can wrap your entire template in a `<script type="text/html" data-ts-template="...">` element, which will be replaced by a `div` element upon template expansion.
