### ISSUE TITLE
Widening the browser window does not change the number of columns

### ISSUE THREAD

**Issue by michelemottini** [Treesaver/treesaver#260]
Using a layout with one, two and three columns, starting with a narrow browser window using the one column layout and then widened the window the layout does not change to two and three columns. Starting from wide and going to narrow works ok.

Tested on Windows 7 with both IE9 and FireFox 6.

**Comment by fortes** [comment]
This is because the narrow templates do not have a `max-width` set on them -- so although the width increases, the existing pages are still within an acceptable range. This is an optimization in order to reduce re-layout -- this does hit people once in a while, not sure if it's just a matter of documentation or if the model is incorrect.

Anyway, try setting `max-width` on that grid and that should do the trick.

**Comment by michelemottini** [comment]
max-width does the trick, thanks.

I would not say that the model is incorrect - it is just a detail to keep in
mind
- Michele
