### ISSUE TITLE
URLs containing '&' are not handled correctly in the TOC

### ISSUE THREAD

**Issue by michelemottini** [Treesaver/treesaver#261]
URLs containing '&' - e.g. 'do.ashx?cmd=feed&name=treesaver&ids=41196'  do not work correclty in the TOC because the apersands are HTML-escaped, so that the end result in the above case is 'do.ashx?cmd=feed&amp;name=treesaver&amp;ids=41196

The problem appear to be in treesaver.template.expandObject_, at line 4710 there is a:

```
          text = treesaver.template.escapeHTML(value);
```

that should possibly be:

```
        if (mapName) {
          text = value;
        }
        else {
          // Inserting normal text - we have to escape HTML characters
          text = treesaver.template.escapeHTML(value);
        }
```

**Comment by bramstein** [comment]
I think the templating code is actually doing the correct thing here, ampersands should be escaped (even in anchors/attributes.) The actual problem is that treesaver 0.9.2 doesn't handle URLs with query parameters correctly. This has been fixed in 0.9.3-beta. Is it an option for you to upgrade to the 0.9.3 beta? You can grab a copy here: https://github.com/bramstein/treesaver/downloads

Please note that the TOC and templating are significantly different from 0.9.2. We are working on updating our documentation, but for now you can have a look at the examples in the Treesaver repository as they are all written for 0.9.3.

**Comment by michelemottini** [comment]
Yes, ampersand should be escaped in the HTML text representation, but if you
are setting an attribute using the DOM - that is what the code is doing
there:

  el.setAttribute(mapName, text)
- you don't have to do the escaping because you are bypassing the HTML
  parser. You have to do the escaping if you use the string direclty as HTML
  or you use it to set innerHTML - that is what the code does if mapName is
  not defined.

I already patched the code, so I can work ok for now. I'd give a try to
0.9.3, but first I want to get a better hang of things - I want to play a
little bit with the TOC and the chrome

  Thanks
- Michele

**Comment by bramstein** [comment]
Ah, I see the problem now. So ampersands would get double escaped, once by the escapeHTML and then once again by setAttribute resulting in `&amp;amp`. Sorry, I didn't get that before---I thought it was related to how Treesaver 0.9.2 handles URLs with query parameters. Your fix is correct, but the template code has been replaced by Mustache.js in 0.9.3 so I guess there isn't much point in patching things (which we'll hopefully release very soon now.)

Thanks a lot for reporting.

**Comment by michelemottini** [comment]
Thank you for looking into it. I'll keep my patch until I upgrade to 0.9.3
- Michele
