### ISSUE TITLE
getElementsByProperty needs to account for special attributes like class and for

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#31]
Not currently being used in the code base, but may bite us later on.

**Comment by bramstein** [comment]
There is (or rather was) actually a unit test that fails because it tried to query on class values using the getElementsByProperty fallback for browsers that do not have querySelectorAll. I fixed this for class names, but it needs a better general solution (i.e. the tests pass now, and the code works, but it needs more work.)

**Comment by bramstein** [comment]
Oh, also the regex expression in the fallback did not escape values, so any value passed to getElementsByProperty that has meaning in regular expressions would break the code. I fixed this by escaping those values.

**Comment by andreacampi** [comment]
getElementsByProperty has been removed so this is moot.
