### ISSUE TITLE
Images within FIgures require explicit size (was: FF/IE/Opera: Text sometimes overlays images)

### ISSUE THREAD

**Issue by bramstein** [Treesaver/treesaver#71]
In certain circumstances text is placed on top of images. I haven't been able to reliable reproduce this, but it has happened several times in Firefox, Internet Explorer (6/7) and Opera. Chrome doesn't seem to have the same problem.

**Comment by fortes** [comment]
This may end up being by design for performance reasons, but I re-titled it and keeping it open for now. At the very least, need to document this very thoroughly.

**Comment by indyjones48** [comment]
Great, tool!  But just encountered this same behavior. The img height attribute specifically must be assigned. Seems like an image load-time issue, as I was prototyping on my localhost wamp server and didn't have this problem. Then, when I pushed the code out to my development web server, I did. It's like treesaver can't calculate the image's vert height  fast enough when it's first loading the image and laying out the text columns.

**Comment by indyjones48** [comment]
Oh, I should add that for me on Chrome and FF, the overlay bug only occurred the first time you launch an article--whether by opening the article in a browser tab, or by flipping back and forth between articles in a "magazine".

Reloading the page dispelled the overlay and it didn't occur again upon subsequent reloads (F5)--which makes sense because by then I assume the image was cached.

**Comment by fortes** [comment]
@indyjones48 -- that's exactly the problem. Need to hook up some code to perhaps watch for changes.

But it really is a best practice to hard code the height of the image, because otherwise Treesaver will have to download every image in order to find out its dimensions, which can waste bandwidth and cause poor load time.

**Comment by indyjones48** [comment]
Sure, understood. Just wasn't sure, based on the previous comments, if you'd narrowed down the exact cause for documentation purposes... Did I mention this is a great tool?! :)
