### ISSUE TITLE
Documentation: Make right & left sides of chrome clickable for next/prev

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#97]
Becoming a common metaphor. Alternatively, could force Chrome authors to do this themselves.

---

Update: Doable in Chrome, need to document clearly in Wiki

**Comment by fortes** [comment]
Low priority for now, since Chrome authors can do this themselves.

**Comment by bramstein** [comment]
I had a quick look at this, and it might be a bit more complicated than just adding some absolutely positioned elements with class `prev` and `next. The main issue is when the areas overlap the current page and obscure links or other content that can be clicked. Selecting those will trigger the previous or next page. Since the Treesaver layout is adaptive, it is difficult set a click area that is consistent across screen sizes. Or perhaps we should limit this to touch devices that have fixed screen sizes (and can thus be fixed for those Chrome templates.)

**Comment by fortes** [comment]
This is a z-order issue, no? If `prev` and `next` divs are below the viewer, shouldn't be an issue, correct?

**Comment by bramstein** [comment]
Ah yes, that would be the obvious simple solution (slaps forehead.) I've added it to the simple test demo per SHA: 666c29538165f66d19c8f234672ab72d0c23f0da

**Comment by fortes** [comment]
Works in demo. Changing this to a documentation issue.
